// <auto-generated />
namespace WilmerRentCar.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intial2323235 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial2323235));
        
        string IMigrationMetadata.Id
        {
            get { return "202003172002193_intial2323235"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
